##############################
# KNIME Server Configuration #
##############################

# Overview of Docker Compose:
# https://docs.docker.com/compose/

# Docker Compose v3:
# https://docs.docker.com/compose/compose-file/compose-file-v3/

# The Compose Specification:
# https://github.com/compose-spec/compose-spec/blob/master/spec.md

services:

  knime-server:
    build:
      context: .
      dockerfile: docker/Server.Dockerfile
      args:
        INSTALLER_URL: "https://download.knime.com/server/4.12/4.12.1/"
        INSTALLER_FILE_PATH: "knime-server-installer-4.12.1.0046-4cb4a5b.jar"
    ports:
      - 8080:8080
      - 8443:8443
    mac_address: "${MAC_ADDRESS}"
    depends_on:
      - rabbitmq

  knime-executor:
    build:
      context: .
      dockerfile: docker/Executor.Dockerfile
      args:
        KNIME_EXEC_VERSION: "4.3.2"
        INSTALLER_URL: "https://download.knime.com/analytics-platform/linux/"
        INSTALLER_FILE_PATH: "knime-full-latest43-linux.gtk.x86_64.tar.gz"
        KNIME_EXECUTOR_MSGQ: "amqp://knime:knime@rabbitmq:5672/knime-server"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    environment:
        RABBITMQ_DEFAULT_USER: knime
        RABBITMQ_DEFAULT_PASS: knime
        RABBITMQ_DEFAULT_VHOST: knime-server
    ports:
        - 5672:5672
        - 15672:15672
 