##############################
# KNIME Server Configuration #
##############################

# Overview of Docker Compose:
# https://docs.docker.com/compose/

# Docker Compose v3:
# https://docs.docker.com/compose/compose-file/compose-file-v3/

# The Compose Specification:
# https://github.com/compose-spec/compose-spec/blob/master/spec.md

services:

  knime-server:
    build:
      context: .
      dockerfile: docker/Serverwithexecutor.Dockerfile
      args:
        INSTALLER_URL: "https://download.knime.com/server/4.12/4.12.1/"
        INSTALLER_FILE_PATH: "knime-server-installer-4.12.1.0046-4cb4a5b.jar"
    ports:
      - 8080:8080
      - 8443:8443
    mac_address: "${MAC_ADDRESS}"